.PHONY: clean All

All:
	@echo "----------Building project:[ Amazon - Debug ]----------"
	@cd "C:\Users\FACOMP\git\Amazon\Amazon" && "$(MAKE)" -f  "Amazon.mk"
clean:
	@echo "----------Cleaning project:[ Amazon - Debug ]----------"
	@cd "C:\Users\FACOMP\git\Amazon\Amazon" && "$(MAKE)" -f  "Amazon.mk" clean
